/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.TreeMap;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        TreeMap<String, String> hauptstaedte = new TreeMap<>();
        hauptstaedte.put("Deutschland", "Berlin");
        hauptstaedte.put("Australien", "Canberra");
        hauptstaedte.put("Frankreich", "Paris");

        System.out.println(hauptstaedte);
    }
}
