/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.HashSet;
import java.util.Set;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Set<Person> peersonSet = new HashSet<>();

        Person p1 = new Person("Peter", "Muster");
        Person p2 = new Person("Peterr", "Muster");



        System.out.println("code: " + p1.hashCode());
        System.out.println("code: " + p2.hashCode());

        peersonSet.add(p1);
        peersonSet.add(p2);

        System.out.println("size: " + peersonSet.size());



     

    }
}
