/*
 * This source file was generated by the Gradle 'init' task
 */
package org.flashcards;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Karteikarten-01";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Game testGame = new Game();

        Scanner scan = new Scanner(System.in);

        testGame.setUp(scan);


    } 
}
