/*
 * This source file was generated by the Gradle 'init' task
 */
package org.flashcards;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Game game = new Game();
        // One scanner for global use
        Scanner scanner = new Scanner(System.in);
        // Build game
        game.setup(scanner);
        // Play game
        game.play(scanner);

        scanner.close();

    } 
}
