/*
 * This source file was generated by the Gradle 'init' task
 */
package org.flashcards;

import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Karteikarten-01";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Scanner scan = new Scanner(System.in);

        System.out.println("How old are you ");
        Integer age = scan.nextInt();

        System.err.println("you are " + age + " old");
    } 
}
