/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;

import reutlingenuniversity.vocabtrainer.model.Vocabulary;

public class VocabularyTest {


    @Test public void getGermanWord_isString() {

        // arrange
        Vocabulary testVocabulary = new Vocabulary("haus", "house");

        // act
        String germanWord = testVocabulary.getGermanWord();

        // assert
        boolean isString = !germanWord.isEmpty() && (germanWord instanceof String);
        assert(isString);
    }
}


