/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner();
        boolean exit = false;
        while (!exit) {
            System.out.println("Please select an option");
            System.out.println("1: Add Word");
            System.out.println("2: Get Word Counts");
            System.out.println("3: Get total number of words");
            System.out.println("4: Get most frequent word");
            System.out.println("5: Get least frequent word (last lexicographic)");
            System.out.println("0: Exit");
            String choice = scanner.nextLine();
            switch (choice) {
                case "1":
                    // Implement your solution
            }
        }
    }
}
