/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        AuthenticationManager account = new AuthenticationManager();

        Scanner scanner = new Scanner(System.in);
        boolean exit = false;
        while (!exit) {
            System.out.println("Enter 1 to register or 2 to login or 0 to end");
            String selection = scanner.nextLine();
            String username;
            String password;
            switch (selection) {
                case "1":
                    System.out.println("LOGIN: \n");
                    System.out.println("Please enter your username: ");
                    username = scanner.nextLine();
                    System.out.println("Please enter your password: ");
                    password = scanner.nextLine();

                    try {
                        account.registerUser(username, password);

                    } catch (RegistrationException e) {
                        System.out.println(e);
                        // Hier Code einfügen
                    }
                break;
                case "2":
                    System.out.println("REGISTER: \n");
                    System.out.println("Please enter your username: ");
                    username = scanner.nextLine();
                    System.out.println("Please enter your password: ");

                    try {
                        password = scanner.nextLine();
                        account.login(username, password);
                        
                    } catch (LoginException | AccountLockedException e) {
                        System.out.println(e);
                    }
                break;

                case "0":
                    System.out.println("end...");
                    exit = true;
                    break;
            }
        }

    }
}
