/*
 * This source file was generated by the Gradle 'init' task
 */
package org.reutlingenuniversity.demo;

public class App {


    public static void main(String[] args) {
        System.out.println("Hello World does it work!");
    }
}
